numpy
=============================
  - python 矩陣(科學)運算工具
  - 資料分析、處理非常方便
  - 有名資料分析、機器學習工具如pandas、tensorflow、pytorch皆有支援numpy物件輸入
  - [API](https://docs.scipy.org/doc/numpy-1.13.0/reference/)

## 基本矩陣資訊
* ndarray.ndim
> the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.
陣列的維度
* ndarray.shape
> the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.
幾乘幾的陣列
* ndarray.size
> the total number of elements of the array. This is equal to the product of the elements of shape.
陣列的元素個數
* ndarray.dtype
> an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
矩陣裡的資料型態
* ndarray.itemsize
> the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
矩陣每個元素佔多少byte 

In [2]:
import numpy as np

In [13]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
print('ndim = ',a.ndim)
print('shape = ',a.shape)
print('dtype = ',a.dtype)
print('itemsize = ',a.itemsize)

ndim =  2
shape =  (3, 2)
dtype =  int32
itemsize =  4


## 矩陣宣告、製作

In [26]:
b = np.arange(15) #arange(15) => 產生1*15陣列，值為0~14
c = b.reshape(3,5)#reshape(a,b,c,...) =>把矩陣變成 a*b*c*...
d = np.zeros([3,3,3])#np.zeros(dim) =>產生宣告維度的矩陣，值為0
e = np.ones([2,2])#np.zeros(dim) =>產生宣告維度的矩陣，值為1
       
       
print('b:\n',b)
print('c:\n',c)
print('d:\n',d)
print('e:\n',e)

b:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
c:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
d:
 [[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]
e:
 [[ 1.  1.]
 [ 1.  1.]]


## 矩陣取值，切割(indexing)

In [130]:
f = np.arange(9).reshape(3,3)
print('dim:',f.shape)
print('f:\n',f)
print('f1,1:',f[0,0])
print('f11~f31:',f[0:,0])
print('f11~f13:',f[0,0:])
print('f11~f12:',f[1,:2])

dim: (3, 3)
f:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
f1,1: 0
f11~f31: [0 3 6]
f11~f13: [0 1 2]
f11~f12: [3 4]


## 矩陣運算

In [94]:
g = np.zeros([2,2])
g1 = np.ones([2,2])
i = np.array([[0,1],
              [0,0]])
h1 = g * h  #相對位置相乘
h2 = g.dot(h) #或是寫np.dot(h2,g1)
print('g:\n',g)
print('g+1\n',g + 1)
print('(g+1)*4:\n',(g+1)*4)
print('(g+1)*4/2:\n',(g+1)*4/2)
print('h:\n',h)
print('g * h:\n',g1*h)
print('g X h:\n',np.dot(g1,h))

g:
 [[ 0.  0.]
 [ 0.  0.]]
g+1
 [[ 1.  1.]
 [ 1.  1.]]
(g+1)*4:
 [[ 4.  4.]
 [ 4.  4.]]
(g+1)*4/2:
 [[ 2.  2.]
 [ 2.  2.]]
h:
 [[1 2]
 [3 4]]
g * h:
 [[ 1.  2.]
 [ 3.  4.]]
g X h:
 [[ 4.  6.]
 [ 4.  6.]]


## 內建運算function

In [103]:
i = np.array([[0,1],[2,3]])
j = 1
print('e(i):\n',np.exp(i))
print('e(j):\n',np.exp(j))
print('log(j):\n',np.log(j))
print('squre(i):\n',np.sqrt(i))

e(i):
 [[  1.           2.71828183]
 [  7.3890561   20.08553692]]
e(j):
 2.71828182846
log(j):
 0.0
squre(i):
 [[ 0.          1.        ]
 [ 1.41421356  1.73205081]]


## 矩陣處理
- 轉置 transpose
- 單位矩陣 I
- trace
- 反矩陣 inverse
- 線性解 solve
- [特徵向量 eigenvalues](http://silverwind1982.pixnet.net/blog/post/154593170-%E7%89%B9%E5%BE%B5%E5%90%91%E9%87%8F%28eigenvector%29-%E5%8F%8A-%E7%89%B9%E5%BE%B5%E5%80%BC%28eigenvalue%29-%E7%9A%84%E5%AE%9A)

In [137]:
k = np.array([[1.0, 2.0], [3.0, 4.0]])
y = np.array([5.0, 7.0])
print('k:\n',k)
print('KT:\n',k.transpose())
print('2X2 I:\n',np.eye(2,2))
print('Trace k:\n',np.trace(k))
print('Inverse k:\n',np.linalg.inv(k))
print('Solve kx = y :\n',np.linalg.solve(k,y))
print('Eigenvalues k:\n',np.linalg.eig(k))

k:
 [[ 1.  2.]
 [ 3.  4.]]
KT:
 [[ 1.  3.]
 [ 2.  4.]]
2X2 I:
 [[ 1.  0.]
 [ 0.  1.]]
Trace k:
 5.0
Inverse k:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Solve kx = y :
 [-3.  4.]
Eigenvalues k:
 (array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


### 其他進階功能
- 邏輯運算

In [121]:
l = np.arange(15).reshape([3,5])
m = np.array([[0,1],
              [1,0]])
print('k:\n',k)
print('if k > 6:\n',k > 6)
print('l or 1:\n',l | 1)
print('l and 0:\n',l & 0)
print('l xor 0:\n',l ^ 0)
print('l not:\n',np.logical_not(l))

k:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
if k > 6:
 [[False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]]
l or 1:
 [[1 1]
 [1 1]]
l and 0:
 [[0 0]
 [0 0]]
l xor 0:
 [[0 1]
 [1 0]]
l not:
 [[ True False]
 [False  True]]
