In [19]:
import tensorflow as tf
import numpy as np

## tf.flags 自行定義變數 在整個ＡＰＰ中都可以呼叫使用 共有boolean,string,integer可以使用
```python
tf.flags.DEFINE_STRING(flag_name, default_value, docstring)
```
### 範例：

In [12]:
tf.flags.DEFINE_boolean('arg1',1,'DOC1')
tf.flags.DEFINE_string('arg2','AAA','DOC2')
FLAGS = tf.flags.FLAGS
tf.flags.DEFINE_string
def main(unused_argv):
    print(FLAGS.arg1)
    print(FLAGS.arg2)

if __name__ == '__main__':
    tf.app.run()

## tf.placeholder 定義訓練的神經元
```python
placeholder(
    dtype,
    shape=None,
    name=None
)
```
### 範例：

In [20]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
#   print(sess.run(y))  # ERROR: will fail because x was not fed.

  rand_array = np.random.rand(1024, 1024)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[247.10553 251.22195 249.5197  ... 255.24889 255.56406 253.80168]
 [241.13722 249.23569 241.33403 ... 247.44556 251.98639 251.13799]
 [242.49358 254.21214 243.80066 ... 250.4488  247.464   249.00139]
 ...
 [240.20596 249.10327 240.72308 ... 247.52448 246.32814 241.11885]
 [244.54626 248.3139  249.3395  ... 251.72047 257.3321  250.81496]
 [245.31879 254.13234 247.6822  ... 254.4111  256.85776 249.55699]]


## tf.variable() 創立變數 ，可用在weight , bias...等等
## tf.get_variable(name) 取得變數，如果沒有則直接創立一個變數 


### 範例：

In [21]:
state = tf.Variable(0, name='counter')
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

init = tf.global_variables_initializer()  
 
# 使用 Session
with tf.Session() as sess:
    sess.run(init)
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

1
2
3


## tf.name_scope() 把tf.variable分類管理，以實現共享機制
name_scope(name)

### 範例：

In [ ]:
with tf.variable_scope("a_variable_scope") as scope:
    initializer = tf.constant_initializer(value=3)
    var3 = tf.get_variable(name='var3', shape=[1], dtype=tf.float32, initializer=initializer)
    scope.reuse_variables()
    var3_reuse = tf.get_variable(name='var3',)
    var4 = tf.Variable(name='var4', initial_value=[4], dtype=tf.float32)
    var4_reuse = tf.Variable(name='var4', initial_value=[4], dtype=tf.float32)
    
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(var3.name)            # a_variable_scope/var3:0
    print(sess.run(var3))       # [ 3.]
    print(var3_reuse.name)      # a_variable_scope/var3:0
    print(sess.run(var3_reuse)) # [ 3.]
    print(var4.name)            # a_variable_scope/var4:0
    print(sess.run(var4))       # [ 4.]
    print(var4_reuse.name)      # a_variable_scope/var4_1:0
    print(sess.run(var4_reuse)) # [ 4.]